title: "Jardim de Lior"
description: "A garden for light, art, and connection"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

locale: "en"
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

author:
  name: "Jardim de Lior"

minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
